// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Is-5f5rz812pnkGkMleaVgSzZE-6xPM',
    appId: '1:292612135121:web:3792c6ca58875625548df0',
    messagingSenderId: '292612135121',
    projectId: 'flash-chat-foo',
    authDomain: 'flash-chat-foo.firebaseapp.com',
    storageBucket: 'flash-chat-foo.firebasestorage.app',
    measurementId: 'G-R6ZSV41BWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnp7SQ9NaxQLQbec9pcU_BDcOA10KXKTQ',
    appId: '1:292612135121:android:e83cfaa9852efb26548df0',
    messagingSenderId: '292612135121',
    projectId: 'flash-chat-foo',
    storageBucket: 'flash-chat-foo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Is-5f5rz812pnkGkMleaVgSzZE-6xPM',
    appId: '1:292612135121:web:caa44d9fab70a600548df0',
    messagingSenderId: '292612135121',
    projectId: 'flash-chat-foo',
    authDomain: 'flash-chat-foo.firebaseapp.com',
    storageBucket: 'flash-chat-foo.firebasestorage.app',
    measurementId: 'G-ZD15ECGPR5',
  );

}